version: "3.8"
services:
    backend:
        build: ./todo_backend
        volumes:
            - ./todo_backend:/app
        ports:
            - "8000:8000"
    reminder:
        build: ./reminder_service
        volumes:
            - ./reminder_service:/app
        ports:
            - "8001:8001"
    frontend:
        build: ./todo_frontend
        volumes:
            - ./todo_frontend:/app
        ports:
            - "8080:8080"
    nginx:
        image: nginx:1.23-alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - backend
            - reminder
            - frontend