# Generated by Django 5.0.1 on 2024-01-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('In Progress', 'In Progress')], default='Pending', max_length=30),
        ),
    ]
